export const actionTypes = {
  FETCH_PRODUCTUS: "FETCH_PRODUCTUS",
  FETCH_PRODUCTUS_DETAILS: "FETCH_PRODUCTUS_DETAILS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
